# numpy

In [20]:
import numpy as np

a=np.array([20,30,40])
b=np.array([60,70,80])
print(a,b)
print(a+b)
print(a*b)

[20 30 40] [60 70 80]
[ 80 100 120]
[1200 2100 3200]


In [22]:
a=np.array([40,50,"60"])
print(a)

['40' '50' '60']


In [8]:
l1=[20,30,40]
l2=[50,60,70]
print(l1+l2)

[20, 30, 40, 50, 60, 70]


In [12]:
l1=[20,30]
l2=5
print(l1*l2)

[20, 30, 20, 30, 20, 30, 20, 30, 20, 30]


# creating arrays slicing and attributes

In [27]:
import numpy as np

In [33]:
arr1=np.array([10,20,30,40])
print(arr1)
print(type(arr1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [51]:
arr2=np.array([[2,4,6,8,0],[1,3,5,7,9]])
print(arr2)


[[2 4 6 8 0]
 [1 3 5 7 9]]


In [57]:
# slicing
arr3=np.array([2,3,4,5,6,7])
print(arr3[0:5])
print(arr3[0:]) #for end value


[2 3 4 5 6]
[2 3 4 5 6 7]


In [75]:
arr=np.array([[10,30,50],[20,30,60]])
print(arr[0:2,0:1])
print(arr[0,0:2])
print(arr[1,0:])

[[10]
 [20]]
[10 30]
[20 30 60]


# attributes

In [85]:

arr=np.array([[10,30,50],[20,30,60],[2,3,5]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(3, 3)
9
2
int32


# functions

In [109]:
arr=np.array([1,2,3,4,5,6])
print(arr.shape)  # rows,col
print(len(arr))   # num of nested values
print(arr.ndim)   
print(arr.size)
print(arr.dtype)     # data type of arr
print(arr.astype(int))

(6,)
6
1
6
int32
[1 2 3 4 5 6]


# mathematical operations and func on arrays

In [121]:
arr1=np.array([[30,40],[60,10]])
arr2=np.array([[10,20],[40,50]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 40  60]
 [100  60]]
[[ 40  60]
 [100  60]]


In [127]:
arr1=np.array([[30,40],[60,10]])
arr2=np.array([[10,20],[40,50]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[ 20  20]
 [ 20 -40]]
[[ 20  20]
 [ 20 -40]]


In [131]:
arr1=np.array([[30,40],[60,10]])
arr2=np.array([[10,20],[40,50]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[ 300  800]
 [2400  500]]
[[ 300  800]
 [2400  500]]


In [133]:
arr1=np.array([[30,40],[60,10]])
arr2=np.array([[10,20],[40,50]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[3.  2. ]
 [1.5 0.2]]
[[3.  2. ]
 [1.5 0.2]]


In [137]:
#power
arr1=np.array([20,30,40,50])
arr2=np.array([3])
print(np.power(arr1,arr2))



[  8000  27000  64000 125000]


In [141]:
arr1=np.array([9,64,8,1])
print(np.sqrt(arr1))

[3.         8.         2.82842712 1.        ]


# combining and splitting arrays

In [160]:
a=[30,40,50]
b=[5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [184]:
#concatenate
import numpy as np
arr1=np.array([[30,40],[50,10]])
arr2=np.array([[5,5],[3,2]])
print(np.concatenate([arr1,arr2]))
#print(arr1+arr2)

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  2]]


In [192]:
print(np.concatenate([arr1,arr2],axis=1))

[[30 40  5  5]
 [50 10  3  2]]


In [194]:
print(np.hstack([arr1,arr2]))  #horizontal concatenation

[[30 40  5  5]
 [50 10  3  2]]


In [200]:
print(np.vstack([arr1,arr2]))  #vertical stack

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  2]]


In [212]:
a=np.array([20,30,40,10,50])
print(np.array_split(a,3))

[array([20, 30]), array([40, 10]), array([50])]


In [214]:
a=np.array([20,30,40,10,50])
b=np.array_split(a,3)
print(b[1])

[40 10]


In [224]:
a=np.array([[20,30,40],[10,50,60]])
b=np.array_split(a,3)
print(b)

[array([[20, 30, 40]]), array([[10, 50, 60]]), array([], shape=(0, 3), dtype=int32)]


# adding and removing elements in the array

In [229]:
import numpy as np

a=np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [233]:
a=np.array([[20,40],[60,80]])
print(np.append(a,90))

[20 40 60 80 90]


In [241]:
a=np.array([20,40,60,80])
print(np.append(a,[90,100,110]))

[ 20  40  60  80  90 100 110]


In [243]:
print(np.insert(a,1,30))

[20 30 40 60 80]


In [247]:
a=np.array([[20,30,40],[30,40,60]])
print(np.insert(a,1,[90,95],axis=1))

[[20 90 30 40]
 [30 95 40 60]]


In [257]:
print(a)
print(np.delete(a,1))

[[20 30 40]
 [30 40 60]]
[20 40 30 40 60]


# sort ,search,filter

In [261]:
import numpy as np

In [263]:
arr=np.array([30,4,5,100])
print(np.sort(arr))

[  4   5  30 100]


In [265]:
arr=np.array([[30,4,5,100],[40,10,3,200]])
print(np.sort(arr))

[[  4   5  30 100]
 [  3  10  40 200]]


In [271]:
arr=np.array([3,4,1,7,8])
#s=np.where(arr==1)
s=np.where(arr%2==0)
print(s)

(array([1, 4], dtype=int64),)


In [277]:
#search sorted 
ar=np.array([1,2,3,4,5,6])
ss=np.searchsorted(ar,5)
print(ss)


4


In [279]:
#filter
ar=np.array([20,30,40,50])
fa=[True,False,True,False]
new_ar=ar[fa]
print(new_ar)

[20 40]


In [281]:
ar=np.array([20,30,40,50])
fa=ar>35
new_ar=ar[fa]
print(new_ar)

[40 50]


# aggregating functions in numpy

In [284]:
import numpy as np

In [306]:
a=np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [330]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]

price=np.array(a)
quantity=np.array(b)

print(price,"\n",quantity)

c=np.cumprod([price,quantity],axis=0)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
31270


# statistical functions in numpy

In [362]:
import numpy as np
import statistics as stats

In [370]:
baked_food=[200,300,150,130,200,280,170,180]
a=np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))


201.25
190.0


In [368]:
from scipy import stats

baked_food=[200,300,150,130,200,280,170,180]
a=np.array(baked_food)
print(stats.mode(a))

ModeResult(mode=200, count=2)
