# numpy

In [3]:
import numpy as np

In [5]:
# 1d array , vector
arr1=np.array([1,2,3,4])

print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
# 2d array ,matrix
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3d array ,tensor
arr3=np.array([[[1,2,3],[4,5,6]],[[10,11,12],[7,8,9]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [ 7  8  9]]]


In [11]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [13]:
# np.arange value i is include j is excluded 
#np.arange(1,11)
np.arange(1,12,3)

array([ 1,  4,  7, 10])

In [15]:
# with reshape defining the rows and column
np.arange(1,11).reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
# np.ones and np.zeros

np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# np.random
np.random.random((3,4))

array([[0.74525252, 0.63864503, 0.51945105, 0.7924204 ],
       [0.41911449, 0.02382617, 0.30699115, 0.90467704],
       [0.09791299, 0.38123378, 0.12049973, 0.51190983]])

In [23]:
# np.linspace -linearly space i-lower range, j-uppr range,k-num of numbers to generate
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [25]:
# np.identity - diagonal matrix is 0ne rest are 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [28]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)



In [30]:
# ndim
a3.ndim

3

In [32]:
# shape
a2.shape

(3, 4)

In [34]:
# size
a3.size

8

In [36]:
# itemsize
a3.itemsize

4

In [38]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# changing data types

In [41]:
# astype()
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operations

In [44]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
# scalar operations 
# arithmetic

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [48]:
# relational
a2>5
#a2==15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
# vector operations 
# arithmetic
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

 # Array functions

In [53]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[30., 99., 92.],
       [73.,  6., 53.],
       [68., 55., 19.]])

In [55]:
# max,min,sum,product 0-columns, 1-row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

np

99.0
6.0
495.0
450733108161600.0


<module 'numpy' from 'C:\\Users\\namde\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [71]:
# mean / median/ std/var

#np.mean(a1,axis=1)
#np.median(a1)
#np.std(a1)
np.var(a1)

902.6666666666666

In [77]:
# dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [81]:
# log and exponents
np.log(a1)
# np.exp(a1)

array([[3.40119738, 4.59511985, 4.52178858],
       [4.29045944, 1.79175947, 3.97029191],
       [4.21950771, 4.00733319, 2.94443898]])

In [85]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[81., 78., 87.],
       [71., 67., 59.]])

In [87]:
np.floor(np.random.random((2,3))*100)

array([[25., 32., 23.],
       [74., 21., 89.]])

# indexing and slicing

In [108]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [98]:
a1[-1]

9

In [104]:
a2[1,3]

7

In [114]:
a3[1,0,1]

5

In [116]:
a3[0,1,0]

2

In [118]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
a1[2:5]
# a1[2:5:2]

array([2, 3, 4])

In [124]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
a2[0,:]

array([0, 1, 2, 3])

In [130]:
a2[1,:]

array([4, 5, 6, 7])

In [132]:
a2[:,2]

array([ 2,  6, 10])

In [134]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [136]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [138]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [156]:
a2[1:2,::3]

array([[4, 7]])

In [194]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [200]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [208]:
a3[0,1,:]

array([3, 4, 5])

In [210]:
a3[1,:,1]

array([10, 13, 16])

# iterating

In [219]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [221]:
for i in a2:
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [223]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [225]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
# reshape
# transpose
# ravel

In [230]:
# transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [232]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# stacking

In [ ]:
# horizontal stacking
#vertical stacking 

In [ ]:
# splitting
