# Numpy tricks

# np.sort 
#Return a sorted copy of an array

In [4]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([ 8, 38, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [6]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[69, 80, 59,  5],
       [84, 19, 43, 60],
       [38, 32, 41, 16],
       [73, 60, 71, 32],
       [34, 73, 22, 83],
       [43, 36, 48, 14]])

In [8]:
# numpy.sort(a, axis=1/0, kind=None, Order=None) ... for desc [::-1]
np.sort(a)
#np.sort(a)[::-1]

array([ 8, 21, 26, 31, 38, 42, 44, 54, 56, 68, 68, 80, 92, 95, 97])

In [10]:
np.sort(b,axis=0)

array([[34, 19, 22,  5],
       [38, 32, 41, 14],
       [43, 36, 43, 16],
       [69, 60, 48, 32],
       [73, 73, 59, 60],
       [84, 80, 71, 83]])

# np. append

In [13]:
# The numpy.append() appends values along the mentioned axis at the end of the array

In [15]:
# code
np.append(a,200)

array([  8,  38,  97,  56,  44,  68,  21,  54,  80,  92,  95,  42,  26,
        31,  68, 200])

In [17]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[69., 80., 59.,  5.,  1.],
       [84., 19., 43., 60.,  1.],
       [38., 32., 41., 16.,  1.],
       [73., 60., 71., 32.,  1.],
       [34., 73., 22., 83.,  1.],
       [43., 36., 48., 14.,  1.]])

# np.concatenate


In [20]:
#numpy.concatenate() function concatenate a squence of arrays along on existing axis

In [22]:
# code 
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [24]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.unique

In [27]:
# with the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method

In [29]:
# code
e=np.array([1,2,3,3,4,5,4,54,5,4,5,4,3,3,3,2,2])
np.unique(e)

array([ 1,  2,  3,  4,  5, 54])

# np.expand_dims

In [32]:
# with the help of numpy.expand_dims() method, we can get the expanded dimensions of an array

In [34]:
# code
a.shape

(15,)

In [36]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [38]:
np.expand_dims(a,axis=0).shape

(1, 15)

# np.where

In [41]:
# The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied

In [43]:
a

array([ 8, 38, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [54]:
# find all the indices with value greater than 50
np.where(a>50)

(array([ 2,  3,  5,  7,  8,  9, 10, 14], dtype=int64),)

In [56]:
# replace all values  >50 with 0 np.where(condition,true,false)
np.where(a>50,0,a)

array([ 8, 38,  0,  0, 44,  0, 21,  0,  0,  0,  0, 42, 26, 31,  0])

In [58]:
# even num replace with 0
np.where(a%2==0,0,a)

array([ 0,  0, 97,  0,  0,  0, 21,  0,  0,  0, 95,  0,  0, 31,  0])

# np.argmax

In [ ]:
# The numpy.argmax() function return indices of the max element of the array in a particular axis

In [61]:
# code
a

array([ 8, 38, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [63]:
b

array([[69, 80, 59,  5],
       [84, 19, 43, 60],
       [38, 32, 41, 16],
       [73, 60, 71, 32],
       [34, 73, 22, 83],
       [43, 36, 48, 14]])

In [65]:
np.argmax(a)

2

In [71]:
np.argmax(b,axis=1) # row

array([1, 0, 2, 0, 3, 2], dtype=int64)

In [73]:
# np.argmin()
np.argmin(a)

0

# np.cumsum

In [ ]:
# numpy.cumsum() func is used when we want to compute the cumulative sum of arr elemnts of the given axis

In [78]:
a

array([ 8, 38, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [82]:
np.cumsum(a)

array([  8,  46, 143, 199, 243, 311, 332, 386, 466, 558, 653, 695, 721,
       752, 820])

In [84]:
b

array([[69, 80, 59,  5],
       [84, 19, 43, 60],
       [38, 32, 41, 16],
       [73, 60, 71, 32],
       [34, 73, 22, 83],
       [43, 36, 48, 14]])

In [88]:
np.cumsum(b,axis=1)

array([[ 69, 149, 208, 213],
       [ 84, 103, 146, 206],
       [ 38,  70, 111, 127],
       [ 73, 133, 204, 236],
       [ 34, 107, 129, 212],
       [ 43,  79, 127, 141]])

In [90]:
# np.cumprod() - it defines the cumulative product
np.cumprod(a)

array([          8,         304,       29488,     1651328,    72658432,
         645806080,   677025792, -2095312896,  -121307136,  1724645376,
         632553472,   797442048,  -741343232, -1506803712,   616562688])

# np.percentile()

In [ ]:
# numpy.percentile() function used to compute the nth percentile of the given data arr along with axis

In [95]:
np.percentile(a,100)

97.0

In [97]:
np.percentile(a,0)

8.0

# np.histogram()

In [ ]:
# it represents the frequency of data distribution in the graphical form

In [102]:
np.histogram(a,bins=[0,50,100])

(array([7, 8], dtype=int64), array([  0,  50, 100]))

# np.corrcoef()

In [ ]:
# return pearson product-moment correlation coefficent

In [107]:
salary=np.array([200000,400000,50000,60000])
experience=np.array([2,3,4,5])

np.corrcoef(salary,experience)

array([[ 1.       , -0.6084533],
       [-0.6084533,  1.       ]])

# np.isin

In [ ]:
# with the help of numpy.isin() method,we can see that one array having values are checked in a different
# numpy arr having different elements with diff size

In [114]:
np.isin(a,[97,23,84,76])

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [118]:
items=[10,30,40,50]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

# np.flip

In [ ]:
# reverse the order of array element in the specified axis but have the same shape

In [121]:
a

array([ 8, 38, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [123]:
np.flip(a)

array([68, 31, 26, 42, 95, 92, 80, 54, 21, 68, 44, 56, 97, 38,  8])

In [125]:
b

array([[69, 80, 59,  5],
       [84, 19, 43, 60],
       [38, 32, 41, 16],
       [73, 60, 71, 32],
       [34, 73, 22, 83],
       [43, 36, 48, 14]])

In [129]:
np.flip(b,axis=0)

array([[43, 36, 48, 14],
       [34, 73, 22, 83],
       [73, 60, 71, 32],
       [38, 32, 41, 16],
       [84, 19, 43, 60],
       [69, 80, 59,  5]])

# np.put()

In [ ]:
# the put func  replaces specific elements of an arr with given value of p_arr
# indexed works on flattened array

In [132]:
a

array([ 8, 38, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [134]:
np.put(a,[0,1],[20,30])

In [136]:
a

array([20, 30, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

# np.delete()

In [139]:
a

array([20, 30, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [143]:
np.delete(a,14)

array([20, 30, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31])

In [145]:
np.delete(a,[0,1,2])

array([56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

# set functions

In [ ]:
 # np.union1d
 # np.intersect1d
 # np.setdiff1d
 # np.setxor1d
 # np.in1d

In [152]:
m=np.array([1,2,3,4,5])
n=np.array([6,7,8,9,0])

np.union1d(m,n)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
np.intersect1d(m,n)

array([], dtype=int32)

In [156]:
np.setdiff1d(m,n)

array([1, 2, 3, 4, 5])

In [158]:
np.setxor1d(m,n)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
np.in1d(m,1)

array([ True, False, False, False, False])

# np.clip()

In [ ]:
# func is used to clip(limit) the values in an array

In [165]:
a

array([20, 30, 97, 56, 44, 68, 21, 54, 80, 92, 95, 42, 26, 31, 68])

In [167]:
np.clip(a,a_min=25, a_max=75)

array([25, 30, 75, 56, 44, 68, 25, 54, 75, 75, 75, 42, 26, 31, 68])